package com.example.booking.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "booking")
public class Booking {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey 
    private String bookingReferenceCode;
    

    // Booking Information
    @DynamoDBAttribute 
    private int numberOfNight;
    @DynamoDBAttribute
    private String startDate;
    @DynamoDBAttribute
    private String endDate;
    @DynamoDBAttribute
    private int numOfAdults;
    @DynamoDBAttribute
    private int numOfKids;
    @DynamoDBAttribute
    private String requestMessage;
    @DynamoDBAttribute
    private String roomType;

    @DynamoDBAttribute
    private Customer customer;


    public String getBookingReferenceCode() {
        return this.bookingReferenceCode;
    }

    public void setBookingReferenceCode(String bookingReferenceCode) {
        this.bookingReferenceCode = bookingReferenceCode;
    }

    public int getNumberOfNight() {
        return this.numberOfNight;
    }

    public void setNumberOfNight(int numberOfNight) {
        this.numberOfNight = numberOfNight;
    }

    public String getStartDate() {
        return this.startDate;
    }

    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    public String getEndDate() {
        return this.endDate;
    }

    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    public int getNumOfAdults() {
        return this.numOfAdults;
    }

    public void setNumOfAdults(int numOfAdults) {
        this.numOfAdults = numOfAdults;
    }

    public int getNumOfKids() {
        return this.numOfKids;
    }

    public void setNumOfKids(int numOfKids) {
        this.numOfKids = numOfKids;
    }

    public String getRequestMessage() {
        return this.requestMessage;
    }

    public void setRequestMessage(String requestMessage) {
        this.requestMessage = requestMessage;
    }

    public String getRoomType() {
        return this.roomType;
    }

    public void setRoomType(String roomType) {
        this.roomType = roomType;
    }

    public Customer getCustomer() {
        return this.customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    
    
}
    
