name: unit test

on:
  push:
    branches: [ master ]
    
jobs:
  build-booking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
      
    - name: Build with Maven
      working-directory: ${{env.working-directory}}
    - run: mvn -e -X -B package --file pom.xml
